### ISSUE TITLE
How do you stop prudynt debug logs?

### ISSUE THREAD

**Issue by dparson55** [gtxaspec/prudynt-t#10]
Is it possible to stop prudynt from writing DEBUG log messages? The loglevel in /etc/prudynt.cfg doesn't seem to do it.

![image](https://github.com/user-attachments/assets/29dfb0de-ebda-4f1f-8ddd-fdc02dc88f63)

![image](https://github.com/user-attachments/assets/6fe0a0de-c675-4233-a012-856de268df03)

**Comment by gtxaspec** [comment]
at the moment we have full debug logs enabled for development/support, it will be disabled soon in a future build.

**Comment by dparson55** [comment]
ok thanks
