### ISSUE TITLE
Read-Me does not explain how to install and use this software

### ISSUE THREAD

**Issue by SamBozman** [gtxaspec/prudynt-t#27]
Hi everyone,
I have 2 cameras that have been hacked with the thingino operating system, and it seems to indicate that this software is used to stream RTSP video. The problem is, even though I have a Linux Ubuntu system, I do not know how to install and use this software. Can someone send me a link to documentation and/or a video?

Thanks
Sam Bozman

**Comment by gtxaspec** [comment]
@SamBozman do you have discord or telegram? the folks there can help guide you.  the software is already installed, and can be configured through SSH or partially through the webui

**Comment by themactep** [comment]
Wiki is open to everyone. Read. Write.
